### PR TITLE
[feature] Add random delay before send_data

### PR DESCRIPTION
**Pull request by minhng99**
This can help prevent server overload.

Signed-off-by: Nguyen Quang Minh <hello@minhng99.eu>

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
The agent can recover from failures to send data if the server is unresponsive or if the internet connection of the device is not working.
If the server is overloaded, rather than using these patches, it is advised to scale vertically and/or horizontally the deployment and to optimize the linux system to be able to handle as many connections and open files as possible.
This patch is not a real solution to scaling issues.

What could make sense instead is to add a boot_up delay as we have in openwisp-config: https://github.com/openwisp/openwisp-config/pull/101, which is useful when big power outages happen and many devices boot all at the same time and start sending data all at the same time, the random bootup delay prevents the agents from sending the data all at the same time to the server which is definitely undesirable.

**Comment by minhng99** [comment]
I can't really scale my server right now... but my setup is having an issue whenever I rebooted the server, all the agents send their statistics and failed and just keep trying it again leading to my server getting overloaded when it's just booted up.

Maybe something like an exponential back-off period after sending failed?

**Comment by nemesisdesign** [comment]
Hi @minhng99 

> Maybe something like an exponential back-off period after sending failed could be better?

I created two issues:

- https://github.com/openwisp/openwrt-openwisp-monitoring/issues/107
- https://github.com/openwisp/openwrt-openwisp-monitoring/issues/108

Let's focus our efforts on those, I suggest trying a randomized backoff and a bootup delay on your system and see if that helps.

**Comment by nemesisdesign** [comment]
Superseded by https://github.com/openwisp/openwrt-openwisp-monitoring/pull/111. Thanks for starting the discussion :+1:.

**Pull request closed without merging**
